import Foundation
import SwiftData
import SwiftUI

/// Manages the shopping list: adding from recipes, checking off, clearing, sharing.
@Observable
final class ShoppingListViewModel {

    /// Add all ingredients from a recipe to the shopping list.
    func addRecipeToShoppingList(recipe: Recipe, context: ModelContext) {
        for ingredient in recipe.ingredients {
            let item = ShoppingListItem(
                ingredient: ingredient.original,
                recipeId: recipe.id,
                recipeName: recipe.title,
                category: IngredientCategorizer.categorize(ingredient.original)
            )
            context.insert(item)
        }
        try? context.save()
    }

    /// Remove all items from a specific recipe.
    func removeRecipeItems(recipeId: UUID, context: ModelContext) {
        let predicate = #Predicate<ShoppingListItem> { item in
            item.recipeId == recipeId
        }
        let descriptor = FetchDescriptor<ShoppingListItem>(predicate: predicate)
        if let items = try? context.fetch(descriptor) {
            for item in items {
                context.delete(item)
            }
            try? context.save()
        }
    }

    /// Clear all checked items.
    func clearCheckedItems(context: ModelContext) {
        let predicate = #Predicate<ShoppingListItem> { item in
            item.isChecked == true
        }
        let descriptor = FetchDescriptor<ShoppingListItem>(predicate: predicate)
        if let items = try? context.fetch(descriptor) {
            for item in items {
                context.delete(item)
            }
            try? context.save()
        }
    }

    /// Clear the entire shopping list.
    func clearAll(context: ModelContext) {
        let descriptor = FetchDescriptor<ShoppingListItem>()
        if let items = try? context.fetch(descriptor) {
            for item in items {
                context.delete(item)
            }
            try? context.save()
        }
    }

    /// Generate plain text for sharing.
    func shareText(items: [ShoppingListItem]) -> String {
        let grouped = Dictionary(grouping: items.filter { !$0.isChecked }, by: { $0.category })
        let sortedKeys = grouped.keys.sorted()

        var lines: [String] = ["Shopping List", "=============", ""]

        for key in sortedKeys {
            lines.append(key.uppercased())
            for item in grouped[key] ?? [] {
                lines.append("☐ \(item.ingredient) (\(item.recipeName))")
            }
            lines.append("")
        }

        lines.append("— Generated by FetchDish")
        return lines.joined(separator: "\n")
    }
}
